- name: Arvid Bessen
  email: bessen@deshaw.com
  num_commits: 6
  first_commit: 2020-04-03 15:38:29
  github: ArvidJB
- name: Melissa Weber Mendonça
  email: melissawm@gmail.com
  aliases:
  - Melissa Weber Mendonca
  - MelissaWM
  - melissawm
  num_commits: 76
  first_commit: 2020-02-21 16:58:29
  github: melissawm
- name: Saul Shanabrook
  email: s.shanabrook@gmail.com
  num_commits: 1
  first_commit: 2020-03-27 14:38:57
  github: Quansight
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 1
  first_commit: 2020-03-20 10:54:25
  github: Quansight
- name: Marc Udoff
  email: mlucool@gmail.com
  num_commits: 1
  first_commit: 2020-06-12 18:49:22
- name: Aaron Meurer
  email: asmeurer@gmail.com
  num_commits: 335
  first_commit: 2019-11-26 18:13:42
  github: asmeurer
